# Generated by Django 5.1.1 on 2024-09-11 11:49

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50, verbose_name='Length of stay')),
                ('image1', models.ImageField(upload_to=homepage.models.upload_to_static, verbose_name='Image of Room')),
                ('image2', models.ImageField(upload_to=homepage.models.upload_to_static, verbose_name='Image of Room')),
            ],
        ),
    ]
