# Generated by Django 5.1.1 on 2024-09-11 14:10

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='video_file',
            field=models.FileField(null=True, upload_to=homepage.models.upload_to_static),
        ),
    ]
